### ISSUE TITLE
Suggestion: Utilising Docker

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [openshiporg/openship#8]
This project could benefit from utilising Docker.

At least for local development a `docker-compose.yml` would make setting up postgress simple:

```
version: '3.8'
services:
    database:
        image: 'postgres:14.1-alpine'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=openship
        expose:
            - '5435'
        ports:
            - '5435:5432'
        volumes:
            - './.cache/db/data:/var/lib/postgresql/data'
            - './.cachec/db/init:/docker-entrypoint-initdb.d'
            
```

Running / Deploying keystone via docker is also pretty simple, but there are a heap of ways you can do it so I won't drop all the code here.

Thoughts?
